version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  mongo-seed-retailers:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./seed-data:/seed-data
    command:
      'bash -c "mongoimport --host mongodb --db test --collection retailers --type json --file /seed-data/retailers.json --jsonArray"'

  mongo-seed-fly-rods:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./seed-data:/seed-data
    command:
      'bash -c "mongoimport --host mongodb --db test --collection fly_rods --type json --file /seed-data/fly-rods.json --jsonArray"'

  api:
    build:
      context: api
      dockerfile: Dockerfile
      args:
        - database=dev
    ports:
      - "8080:8080"
    depends_on:
      - mongo-seed-retailers
      - mongo-seed-fly-rods
      - mongodb
