apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-tier
spec:
  replicas: 1
  template:
    metadata:
      name: api-tier
      labels:
        app: app
        tier: api
    spec:
      containers:
        - name: golang
          image: golang:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
